# Generated by Django 4.1.5 on 2023-08-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('policy_cover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('policy_status', models.CharField(choices=[('1', 'Requirements Awaited'), ('2', 'Requirements Closed'), ('3', 'Underwriting'), ('4', 'Policy Issued'), ('5', 'Policy Rejected')], max_length=1)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_type', models.CharField(blank=True, choices=[('1', 'Tele Medicals'), ('2', 'Physical Medicals')], max_length=1, null=True)),
                ('medical_status', models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Scheduled'), ('3', 'Waiting for Report'), ('4', 'Done')], max_length=1, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
